# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: some_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12some_message.proto\"#\n\x07\x46riends\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xfb\x02\n\x04List\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0c\n\x04guid\x18\x03 \x01(\t\x12\x10\n\x08isActive\x18\x04 \x01(\x08\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\t\x12\x0f\n\x07picture\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\r\x12\x10\n\x08\x65yeColor\x18\x08 \x01(\t\x12\x0c\n\x04name\x18\t \x01(\t\x12\x0e\n\x06gender\x18\n \x01(\t\x12\x0f\n\x07\x63ompany\x18\x0b \x01(\t\x12\r\n\x05\x65mail\x18\x0c \x01(\t\x12\r\n\x05phone\x18\r \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x0e \x01(\t\x12\r\n\x05\x61\x62out\x18\x0f \x01(\t\x12\x12\n\nregistered\x18\x10 \x01(\t\x12\x10\n\x08latitude\x18\x11 \x01(\x01\x12\x11\n\tlongitude\x18\x12 \x01(\x01\x12\x0c\n\x04tags\x18\x13 \x03(\t\x12\x19\n\x07\x66riends\x18\x14 \x03(\x0b\x32\x08.Friends\x12\x10\n\x08greeting\x18\x15 \x01(\t\x12\x15\n\rfavoriteFruit\x18\x16 \x01(\t\"\"\n\x0bSomeMessage\x12\x13\n\x04list\x18\x01 \x03(\x0b\x32\x05.Listb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'some_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FRIENDS']._serialized_start=22
  _globals['_FRIENDS']._serialized_end=57
  _globals['_LIST']._serialized_start=60
  _globals['_LIST']._serialized_end=439
  _globals['_SOMEMESSAGE']._serialized_start=441
  _globals['_SOMEMESSAGE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
