version: '3.8'
services:
  pickle:
    build: .
    command: --test pickle
  xml:
    build: .
    command: --test xml
  json:
    build: .
    command: --test json
  proto:
    build: .
    command: --test proto
  avro:
    build: .
    command: --test avro
  yaml:
    build: .
    command: --test yaml
  msgpack:
    build: .
    command: --test msgpack
